In [5]:
import numpy as np

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Step 1: Construct the Covariance Matrix (X.Xt) # transpose
covariance_matrix = np.cov(X.T)

# Step 2: Apply Linear Eigen Decomposition to X.(XT) to Obtain Eigen Values and Vectors
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

# Step 3: Sort Eigenvalues in Decreasing Order to Sort Eigenvectors
idx = eigenvalues.argsort()[::-1]   
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:,idx]

# Step 4: Build Matrix W(d*k) with k Top Eigenvectors
W = eigenvectors[:, :1]

# Step 5: Transform X using W to Obtain the New Subspace Y=X.W
Y = X.dot(W)

print(Y)


[[2.12132034]
 [4.94974747]
 [7.77817459]]


`eigen decomposition`

In [7]:
import numpy as np 

X = np.array([
    [1,2],
    [3,4],
    [5,6]
])

X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# construct the Covariance matrix: multiply X by its transpose:

# given data and weights, estimate the covariance matrix
covariance_matrix = np.cov(X.T)
covariance_matrix 

array([[4., 4.],
       [4., 4.]])

In [12]:
# obtain eigen vectors and values : use linear eigen decomposition:

# computes eigen values and right eigen vectors given a square array
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
eigenvalues, eigenvectors

(array([8., 0.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [15]:
# sort eigen values in decreasing order: this inturn sorts the eigen vectors
idx = eigenvalues.argsort()[::-1]
idx

array([0, 1])

In [16]:
eigenvalues = eigenvalues[idx]
eigenvalues

array([8., 0.])

In [17]:
eigenvectors = eigenvectors[:, idx]
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [22]:
# build a matrix W(d*k) with k top eigenvectors
W = eigenvectors[:, :1]
W

array([[0.70710678],
       [0.70710678]])

In [23]:
# transform X using W to obtain the new subspace
Y = X.dot(W)
Y

array([[2.12132034],
       [4.94974747],
       [7.77817459]])