In [1]:
import pandas as pd 
import numpy as np 

from matplotlib import pyplot as plt 

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris # dataset to be used
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

from sklearn.metrics import accuracy_score

In [2]:
iris = load_iris()
X = iris.data 
y = iris.target 

* number of obseravtions

In [14]:
X.shape[0] # 150

150

* number of features

In [16]:
X.shape[1] # 4

4

In [18]:
# name of the features
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

* classes to predict

In [ ]:
np.unique(y)

array([0, 1, 2])

* target names

In [20]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [27]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [31]:
np.unique(y, return_counts=True)
# for each class, we have same number of observations: 50

(array([0, 1, 2]), array([50, 50, 50]))

In [32]:
pd.options.display.float_format = '{:,.2f}'.format

In [33]:
df.describe()

AttributeError: describe